## Data Cleaning

In [22]:
import pandas as pd
import numpy as np

In [23]:
#import data
data = pd.read_csv('Echocardiogram.csv')
data

,Survival,Still-alive,Age-at-heart-attack,Pericardial-effusion,Fractional-shortening,epss,lvdd,Wall-motion-score,Wall-motion-index,Mult,name,group,Alive-at-1
0,11.00,dead,71.000,no,0.260,9.000,4.600,14.00,1.000,1.000,name,1.0,no
1,19.00,dead,72.000,no,0.380,6.000,4.100,14.00,1.700,0.588,name,1.0,no
2,16.00,dead,55.000,no,0.260,4.000,3.420,14.00,1.000,1.000,name,1.0,no
3,57.00,dead,60.000,no,0.253,12.062,4.603,16.00,1.450,0.788,name,1.0,no
4,19.00,life,57.000,no,0.160,22.000,5.750,18.00,2.250,0.571,name,1.0,no
5,26.00,dead,68.000,no,0.260,5.000,4.310,12.00,1.000,0.857,name,1.0,no
6,13.00,dead,62.000,no,0.230,31.000,5.430,22.50,1.875,0.857,name,1.0,no
7,50.00,dead,60.000,no,0.330,8.000,5.250,14.00,1.000,1.000,name,1.0,no
8,19.00,dead,46.000,no,0.340,0.000,5.090,16.00,1.140,1.003,name,1.0,no
9,25.00,dead,54.000,no,0.140,13.000,4.490,15.50,1.190,0.930,name,1.0,no
10,10.00,life,77.000,no,0.130,16.000,4.230,18.00,1.800,0.714,name,1.0,yes
11,52.00,dead,62.000,yes,0.450,9.000,3.600,16.00,1.140,1.003,name,1.0,no
12,52.00,dead,73.000,no,0.330,6.000,4.000,14.00,1.000,1.000,name,1.0,no
13,44.00,dead,60.000,no,0.150,10.000,3.730,14.00,1.000,1.000,name,1.0,no
14,0.50,life,62.000,no,0.120,23.000,5.800,11.67,2.330,0.358,name,1.0,yes
15,24.00,dead,55.000,yes,0.250,12.063,4.290,14.00,1.000,1.000,name,1.0,no
16,0.50,life,69.000,yes,0.260,11.000,4.650,18.00,1.640,0.784,name,1.0,yes
17,0.50,life,62.529,yes,0.070,20.000,5.200,24.00,2.000,0.857,name,1.0,yes
18,22.00,life,66.000,no,0.090,17.000,5.819,8.00,1.333,0.429,name,1.0,no
19,1.00,life,66.000,yes,0.220,15.000,5.400,27.00,2.250,0.857,name,1.0,yes
20,0.75,life,69.000,no,0.150,12.000,5.390,19.50,1.625,0.857,name,1.0,yes
21,0.75,life,85.000,yes,0.180,19.000,5.460,13.83,1.380,0.710,name,1.0,yes
22,0.50,life,73.000,no,0.230,12.733,6.060,7.50,1.500,0.360,name,1.0,yes
23,5.00,life,71.000,no,0.170,0.000,4.650,8.00,1.000,0.570,name,1.0,yes
24,48.00,dead,64.000,no,0.190,5.900,3.480,10.00,1.110,0.640,name,2.0,NaN
25,29.00,dead,54.000,no,0.300,7.000,3.850,10.00,1.667,0.430,name,2.0,NaN
26,29.00,dead,35.000,no,0.300,5.000,4.170,14.00,1.000,1.000,name,2.0,NaN
27,29.00,dead,55.000,no,NaN,7.000,NaN,2.00,1.000,2.000,name,2.0,NaN
28,0.25,life,75.000,no,NaN,NaN,NaN,NaN,1.000,NaN,name,2.0,NaN
29,36.00,dead,55.000,yes,0.210,4.200,4.160,14.00,1.560,0.640,name,2.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,22.00,dead,70.000,no,0.380,0.000,4.550,10.00,1.000,0.714,name,2.0,no
103,25.00,dead,62.000,no,0.258,11.800,4.870,11.00,1.000,0.786,name,2.0,NaN
104,1.25,life,63.000,no,0.300,6.900,3.520,18.16,1.510,0.857,name,2.0,yes
105,24.00,dead,59.000,no,0.170,14.300,5.490,13.50,1.500,0.643,name,2.0,no
106,25.00,dead,57.000,no,0.228,9.700,4.290,11.00,1.000,0.786,name,2.0,no
107,24.00,dead,57.000,no,0.036,7.000,4.120,13.50,1.230,0.786,name,2.0,NaN
108,0.75,life,78.000,no,0.230,40.000,6.230,14.00,1.400,0.714,name,2.0,yes
109,3.00,life,62.000,no,0.260,7.600,4.420,14.00,1.000,1.000,name,2.0,yes
110,27.00,dead,62.000,no,0.220,12.100,3.920,11.00,1.000,0.785,name,NaN,NaN
111,13.00,dead,66.000,no,0.240,13.600,4.380,22.00,2.200,0.714,name,NaN,NaN
112,36.00,dead,61.000,no,0.270,9.000,4.060,12.00,1.000,0.857,name,NaN,NaN
113,25.00,dead,59.000,yes,0.400,9.200,5.360,12.00,1.000,0.857,name,NaN,NaN
114,27.00,dead,57.000,no,0.290,9.400,4.770,9.00,1.000,0.640,name,NaN,NaN
115,34.00,dead,62.000,yes,0.190,28.900,6.630,19.50,1.950,0.714,name,NaN,NaN
116,37.00,dead,NaN,no,0.260,0.000,4.380,9.00,1.000,0.640,name,NaN,NaN
117,34.00,dead,54.000,no,0.430,9.300,4.790,10.00,1.000,0.714,name,NaN,NaN
118,28.00,life,62.000,yes,0.240,28.600,5.860,21.50,1.950,0.786,name,NaN,NaN
119,28.00,dead,NaN,no,0.230,19.100,5.490,12.00,1.200,0.710,name,NaN,NaN
120,17.00,dead,64.000,no,0.150,6.600,4.170,14.00,1.270,0.786,name,NaN,NaN
121,38.00,dead,57.000,yes,0.120,0.000,2.320,16.50,1.375,0.857,name,NaN,NaN
122,31.00,dead,61.000,no,0.180,0.000,4.480,11.00,1.375,0.570,name,NaN,NaN
123,12.00,dead,61.000,yes,0.190,13.200,5.040,19.00,1.730,0.786,name,NaN,NaN
124,36.00,dead,48.000,no,0.150,12.000,3.660,10.00,1.000,0.714,name,NaN,NaN
125,17.00,dead,NaN,no,0.090,6.800,4.960,13.00,1.080,0.857,name,NaN,NaN
126,21.00,dead,61.000,no,0.140,25.500,5.160,14.00,1.270,0.786,name,NaN,NaN
127,7.50,life,64.000,no,0.240,12.900,4.720,12.00,1.000,0.857,name,NaN,NaN
128,41.00,dead,64.000,no,0.280,5.400,5.470,11.00,1.100,0.714,name,NaN,NaN
129,36.00,dead,69.000,no,0.200,7.000,5.050,14.50,1.210,0.857,name,NaN,NaN
130,22.00,dead,57.000,no,0.140,16.100,4.360,15.00,1.360,0.786,name,NaN,NaN
131,20.00,dead,62.000,no,0.150,0.000,4.510,15.50,1.409,0.786,name,NaN,NaN

In [24]:
data.head(15)

,Survival,Still-alive,Age-at-heart-attack,Pericardial-effusion,Fractional-shortening,epss,lvdd,Wall-motion-score,Wall-motion-index,Mult,name,group,Alive-at-1
0,11.0,dead,71.0,no,0.260,9.000,4.600,14.00,1.000,1.000,name,1.0,no
1,19.0,dead,72.0,no,0.380,6.000,4.100,14.00,1.700,0.588,name,1.0,no
2,16.0,dead,55.0,no,0.260,4.000,3.420,14.00,1.000,1.000,name,1.0,no
3,57.0,dead,60.0,no,0.253,12.062,4.603,16.00,1.450,0.788,name,1.0,no
4,19.0,life,57.0,no,0.160,22.000,5.750,18.00,2.250,0.571,name,1.0,no
5,26.0,dead,68.0,no,0.260,5.000,4.310,12.00,1.000,0.857,name,1.0,no
6,13.0,dead,62.0,no,0.230,31.000,5.430,22.50,1.875,0.857,name,1.0,no
7,50.0,dead,60.0,no,0.330,8.000,5.250,14.00,1.000,1.000,name,1.0,no
8,19.0,dead,46.0,no,0.340,0.000,5.090,16.00,1.140,1.003,name,1.0,no
9,25.0,dead,54.0,no,0.140,13.000,4.490,15.50,1.190,0.930,name,1.0,no
10,10.0,life,77.0,no,0.130,16.000,4.230,18.00,1.800,0.714,name,1.0,yes
11,52.0,dead,62.0,yes,0.450,9.000,3.600,16.00,1.140,1.003,name,1.0,no
12,52.0,dead,73.0,no,0.330,6.000,4.000,14.00,1.000,1.000,name,1.0,no
13,44.0,dead,60.0,no,0.150,10.000,3.730,14.00,1.000,1.000,name,1.0,no
14,0.5,life,62.0,no,0.120,23.000,5.800,11.67,2.330,0.358,name,1.0,yes

In [25]:
data.tail(15)

,Survival,Still-alive,Age-at-heart-attack,Pericardial-effusion,Fractional-shortening,epss,lvdd,Wall-motion-score,Wall-motion-index,Mult,name,group,Alive-at-1
117,34.0,dead,54.0,no,0.43,9.3,4.79,10.0,1.000,0.714,name,NaN,NaN
118,28.0,life,62.0,yes,0.24,28.6,5.86,21.5,1.950,0.786,name,NaN,NaN
119,28.0,dead,NaN,no,0.23,19.1,5.49,12.0,1.200,0.710,name,NaN,NaN
120,17.0,dead,64.0,no,0.15,6.6,4.17,14.0,1.270,0.786,name,NaN,NaN
121,38.0,dead,57.0,yes,0.12,0.0,2.32,16.5,1.375,0.857,name,NaN,NaN
122,31.0,dead,61.0,no,0.18,0.0,4.48,11.0,1.375,0.570,name,NaN,NaN
123,12.0,dead,61.0,yes,0.19,13.2,5.04,19.0,1.730,0.786,name,NaN,NaN
124,36.0,dead,48.0,no,0.15,12.0,3.66,10.0,1.000,0.714,name,NaN,NaN
125,17.0,dead,NaN,no,0.09,6.8,4.96,13.0,1.080,0.857,name,NaN,NaN
126,21.0,dead,61.0,no,0.14,25.5,5.16,14.0,1.270,0.786,name,NaN,NaN
127,7.5,life,64.0,no,0.24,12.9,4.72,12.0,1.000,0.857,name,NaN,NaN
128,41.0,dead,64.0,no,0.28,5.4,5.47,11.0,1.100,0.714,name,NaN,NaN
129,36.0,dead,69.0,no,0.20,7.0,5.05,14.5,1.210,0.857,name,NaN,NaN
130,22.0,dead,57.0,no,0.14,16.1,4.36,15.0,1.360,0.786,name,NaN,NaN
131,20.0,dead,62.0,no,0.15,0.0,4.51,15.5,1.409,0.786,name,NaN,NaN

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 13 columns):
Survival                 130 non-null float64
Still-alive              131 non-null object
Age-at-heart-attack      127 non-null float64
Pericardial-effusion     131 non-null object
Fractional-shortening    124 non-null float64
epss                     117 non-null float64
lvdd                     121 non-null float64
Wall-motion-score        128 non-null float64
Wall-motion-index        131 non-null float64
Mult                     128 non-null float64
name                     132 non-null object
group                    110 non-null float64
Alive-at-1               74 non-null object
dtypes: float64(9), object(4)
memory usage: 13.5+ KB

In [27]:
#statistika deskriptif
data.describe()

,Survival,Age-at-heart-attack,Fractional-shortening,epss,lvdd,Wall-motion-score,Wall-motion-index,Mult,group
count,130.000000,127.000000,124.000000,117.000000,121.000000,128.000000,131.000000,128.000000,110.000000
mean,22.182923,62.925425,0.216734,12.164769,4.763157,14.438125,1.382748,0.776719,1.781818
std,15.858267,8.403757,0.107513,7.370159,0.810013,5.018566,0.453378,0.199078,0.414902
min,0.030000,35.000000,0.010000,0.000000,2.320000,2.000000,1.000000,0.140000,1.000000
25%,7.875000,57.000000,0.150000,7.000000,4.230000,11.000000,1.000000,0.713000,2.000000
50%,23.500000,62.000000,0.205000,11.000000,4.650000,14.000000,1.222000,0.786000,2.000000
75%,33.000000,68.000000,0.270000,16.100000,5.300000,16.500000,1.535000,0.857000,2.000000
max,57.000000,86.000000,0.610000,40.000000,6.780000,39.000000,3.000000,2.000000,2.000000

In [28]:
np.sum(data.isnull())

Survival                  2
Still-alive               1
Age-at-heart-attack       5
Pericardial-effusion      1
Fractional-shortening     8
epss                     15
lvdd                     11
Wall-motion-score         4
Wall-motion-index         1
Mult                      4
name                      0
group                    22
Alive-at-1               58
dtype: int64

In [32]:
# imputasi data kontinu
data['Survival'] = data['Survival'].fillna((data['Survival'].mean())) 
data['Age-at-heart-attack'] = data['Age-at-heart-attack'].fillna((data['Age-at-heart-attack'].mean())) 
data['epss'] = data['epss'].fillna((data['epss'].mean())) 
data['lvdd'] = data['lvdd'].fillna((data['lvdd'].mean()))
data['Wall-motion-score'] = data['Wall-motion-score'].fillna((data['Wall-motion-score'].mean))
data['Wall-motion-index'] = data['Wall-motion-index'].fillna((data['Wall-motion-index'].mean))
data['Mult'] = data['Mult'].fillna((data['Mult'].mean))
data['Fractional-shortening'] = data['Fractional-shortening'].fillna((data['Fractional-shortening'].mean))


data.isnull().any()

Survival                 False
Still-alive              False
Age-at-heart-attack      False
Pericardial-effusion     False
Fractional-shortening    False
epss                     False
lvdd                     False
Wall-motion-score        False
Wall-motion-index        False
Mult                     False
name                     False
group                    False
Alive-at-1               False
dtype: bool

In [29]:
data.head()

,Survival,Still-alive,Age-at-heart-attack,Pericardial-effusion,Fractional-shortening,epss,lvdd,Wall-motion-score,Wall-motion-index,Mult,name,group,Alive-at-1
0,11.0,dead,71.0,no,0.260,9.000,4.600,14.0,1.00,1.000,name,1.0,no
1,19.0,dead,72.0,no,0.380,6.000,4.100,14.0,1.70,0.588,name,1.0,no
2,16.0,dead,55.0,no,0.260,4.000,3.420,14.0,1.00,1.000,name,1.0,no
3,57.0,dead,60.0,no,0.253,12.062,4.603,16.0,1.45,0.788,name,1.0,no
4,19.0,life,57.0,no,0.160,22.000,5.750,18.0,2.25,0.571,name,1.0,no

In [33]:
#imputasi data kategorik
data['Still-alive'] = data['Still-alive'].fillna((data['Still-alive'].value_counts().index[0]))
data['Pericardial-effusion'] = data['Pericardial-effusion'].fillna((data['Pericardial-effusion'].value_counts().index[0]))
data['group'] = data['group'].fillna((data['group'].mode))
data['Alive-at-1'] = data['Alive-at-1'].fillna((data['Alive-at-1'].value_counts().index[0]))
data.isnull().any()

Survival                 False
Still-alive              False
Age-at-heart-attack      False
Pericardial-effusion     False
Fractional-shortening    False
epss                     False
lvdd                     False
Wall-motion-score        False
Wall-motion-index        False
Mult                     False
name                     False
group                    False
Alive-at-1               False
dtype: bool

In [34]:
data.head()

,Survival,Still-alive,Age-at-heart-attack,Pericardial-effusion,Fractional-shortening,epss,lvdd,Wall-motion-score,Wall-motion-index,Mult,name,group,Alive-at-1
0,11.0,dead,71.0,no,0.26,9.000,4.600,14,1,1,name,1,no
1,19.0,dead,72.0,no,0.38,6.000,4.100,14,1.7,0.588,name,1,no
2,16.0,dead,55.0,no,0.26,4.000,3.420,14,1,1,name,1,no
3,57.0,dead,60.0,no,0.253,12.062,4.603,16,1.45,0.788,name,1,no
4,19.0,life,57.0,no,0.16,22.000,5.750,18,2.25,0.571,name,1,no

## Encode Labels

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
# Encode untuk Still-alive, Pericardial-effusion, Alive-at-1 tanpa membuat kolom baru
data['Still-alive'] = LabelEncoder().fit_transform(data['Still-alive'])
data['Pericardial-effusion'] = LabelEncoder().fit_transform(data['Pericardial-effusion'])
data['Alive-at-1'] = LabelEncoder().fit_transform(data['Alive-at-1'])
data.head()

,Survival,Still-alive,Age-at-heart-attack,Pericardial-effusion,Fractional-shortening,epss,lvdd,Wall-motion-score,Wall-motion-index,Mult,name,group,Alive-at-1
0,11.0,0,71.0,0,0.26,9.000,4.600,14,1,1,name,1,0
1,19.0,0,72.0,0,0.38,6.000,4.100,14,1.7,0.588,name,1,0
2,16.0,0,55.0,0,0.26,4.000,3.420,14,1,1,name,1,0
3,57.0,0,60.0,0,0.253,12.062,4.603,16,1.45,0.788,name,1,0
4,19.0,1,57.0,0,0.16,22.000,5.750,18,2.25,0.571,name,1,0

## Standardize

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 13 columns):
Survival                 132 non-null float64
Still-alive              132 non-null int32
Age-at-heart-attack      132 non-null float64
Pericardial-effusion     132 non-null int32
Fractional-shortening    132 non-null object
epss                     132 non-null float64
lvdd                     132 non-null float64
Wall-motion-score        132 non-null object
Wall-motion-index        132 non-null object
Mult                     132 non-null object
name                     132 non-null object
group                    132 non-null object
Alive-at-1               132 non-null int32
dtypes: float64(4), int32(3), object(6)
memory usage: 11.9+ KB

In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
data['Survival'] = StandardScaler().fit(data[['Survival']]).transform(data[['Survival']])
data['Age-at-heart-attack'] = StandardScaler().fit(data[['Age-at-heart-attack']]).transform(data[['Age-at-heart-attack']])
data['epss'] = StandardScaler().fit(data[['epss']]).transform(data[['epss']])
data['lvdd'] = StandardScaler().fit(data[['lvdd']]).transform(data[['lvdd']])

data.head()

,Survival,Still-alive,Age-at-heart-attack,Pericardial-effusion,Fractional-shortening,epss,lvdd,Wall-motion-score,Wall-motion-index,Mult,name,group,Alive-at-1
0,-0.713332,0,0.983440,0,0.26,-0.458061,-0.211257,14,1,1,name,1,0
1,-0.203031,0,1.105235,0,0.38,-0.892273,-0.858659,14,1.7,0.588,name,1,0
2,-0.394394,0,-0.965274,0,0.26,-1.181748,-1.739126,14,1,1,name,1,0
3,2.220898,0,-0.356301,0,0.253,-0.014875,-0.207372,16,1.45,0.788,name,1,0
4,-0.203031,1,-0.721685,0,0.16,1.423527,1.277769,18,2.25,0.571,name,1,0

## Normalize

In [43]:
from sklearn.preprocessing import Normalizer

In [48]:
data['Survival'] = Normalizer ().fit(data[['Survival']]).transform(data[['Survival']])
data['Age-at-heart-attack'] = Normalizer ().fit(data[['Age-at-heart-attack']]).transform(data[['Age-at-heart-attack']])
data['epss'] = Normalizer ().fit(data[['epss']]).transform(data[['epss']])
data['lvdd'] = Normalizer ().fit(data[['lvdd']]).transform(data[['lvdd']])
data.head()

,Survival,Still-alive,Age-at-heart-attack,Pericardial-effusion,Fractional-shortening,epss,lvdd,Wall-motion-score,Wall-motion-index,Mult,name,group,Alive-at-1
0,-1.0,0,1.0,0,0.26,-1.0,-1.0,14,1,1,name,1,0
1,-1.0,0,1.0,0,0.38,-1.0,-1.0,14,1.7,0.588,name,1,0
2,-1.0,0,-1.0,0,0.26,-1.0,-1.0,14,1,1,name,1,0
3,1.0,0,-1.0,0,0.253,-1.0,-1.0,16,1.45,0.788,name,1,0
4,-1.0,1,-1.0,0,0.16,1.0,1.0,18,2.25,0.571,name,1,0